-- begin RKS_DOCUMENT
alter table RKS_DOCUMENT add constraint FK_RKS_DOCUMENT_ON_DOCUMENT_TEMPLATE foreign key (DOCUMENT_TEMPLATE_ID) references RKS_DOCUMENT_TEMPLATE(ID)^
create index IDX_RKS_DOCUMENT_ON_DOCUMENT_TEMPLATE on RKS_DOCUMENT (DOCUMENT_TEMPLATE_ID)^
-- end RKS_DOCUMENT
-- begin RKS_DOCUMENT_TEMPLATE_LINE
alter table RKS_DOCUMENT_TEMPLATE_LINE add constraint FK_RKS_DOCUMENT_TEMPLATE_LINE_ON_DOCUMENT_TEMPLATE foreign key (DOCUMENT_TEMPLATE_ID) references RKS_DOCUMENT_TEMPLATE(ID)^
create unique index IDX_RKS_DOCUMENT_TEMPLATE_LINE_UNQ on RKS_DOCUMENT_TEMPLATE_LINE (NUMBER_, DOCUMENT_TEMPLATE_ID)^
create unique index IDX_RKS_DOCUMENT_TEMPLATE_LINE_UNQ_1 on RKS_DOCUMENT_TEMPLATE_LINE (HEADER, DOCUMENT_TEMPLATE_ID)^
create index IDX_RKS_DOCUMENT_TEMPLATE_LINE_ON_DOCUMENT_TEMPLATE on RKS_DOCUMENT_TEMPLATE_LINE (DOCUMENT_TEMPLATE_ID)^
-- end RKS_DOCUMENT_TEMPLATE_LINE
-- begin RKS_DOCUMENT_VALUE
alter table RKS_DOCUMENT_VALUE add constraint FK_RKS_DOCUMENT_VALUE_ON_DOCUMENT_TEMPLATE_LINE foreign key (DOCUMENT_TEMPLATE_LINE_ID) references RKS_DOCUMENT_TEMPLATE_LINE(ID)^
alter table RKS_DOCUMENT_VALUE add constraint FK_RKS_DOCUMENT_VALUE_ON_DOCUMENT foreign key (DOCUMENT_ID) references RKS_DOCUMENT(ID)^
create index IDX_RKS_DOCUMENT_VALUE_ON_DOCUMENT_TEMPLATE_LINE on RKS_DOCUMENT_VALUE (DOCUMENT_TEMPLATE_LINE_ID)^
create index IDX_RKS_DOCUMENT_VALUE_ON_DOCUMENT on RKS_DOCUMENT_VALUE (DOCUMENT_ID)^
-- end RKS_DOCUMENT_VALUE
-- begin RKS_DOCUMENT_TEMPLATE
create unique index IDX_RKS_DOCUMENT_TEMPLATE_UNIQ_NAME on RKS_DOCUMENT_TEMPLATE (NAME)^
-- end RKS_DOCUMENT_TEMPLATE
