alter table RKS_DOCUMENT add constraint FK_RKS_DOCUMENT_ON_DOCUMENT_TEMPLATE foreign key (DOCUMENT_TEMPLATE_ID) references RKS_DOCUMENT_TEMPLATE(ID);
create index IDX_RKS_DOCUMENT_ON_DOCUMENT_TEMPLATE on RKS_DOCUMENT (DOCUMENT_TEMPLATE_ID);
